"""Agregado telefono

Revision ID: 21ba053f5402
Revises: a0078addda3a
Create Date: 2026-09-18 15:56:45.372797

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "21ba053f5402"
down_revision: Union[str, Sequence[str], None] = "a0078addda3a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("telefono", sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "telefono")
    # ### end Alembic commands ###
