[project]
name = "19-modulo-seguridad-mantenimiento"
version = "0.1.0"
description = ""
authors = [
    {name = "Erick Sebastian Meneses Navarro",email = "erick.meneses@axity.com"}
]
requires-python = ">=3.12, <4.0"
dependencies = [
    "pydantic-settings (>=2.15.0,<3.0.0)",
    "pyjwt (>=2.15.0,<3.0.0)",
    "requests (>=2.34.2,<3.0.0)",
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[dependency-groups]
dev = [
    "pip-audit (>=2.10.1,<3.0.0)"
]
