# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: orders.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC, 7, 35, 1, "", "orders.proto"
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x0corders.proto\x12\x06orders"4\n\x0cOrderRequest\x12\x12\n\nproduct_id\x18\x01 \x01(\t\x12\x10\n\x08quantity\x18\x02 \x01(\x05".\n\nOrderReply\x12\x10\n\x08order_id\x18\x01 \x01(\t\x12\x0e\n\x06status\x18\x02 \x01(\t2I\n\x0cOrderService\x12\x39\n\x0b\x43reateOrder\x12\x14.orders.OrderRequest\x1a\x12.orders.OrderReply"\x00\x62\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "orders_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals["_ORDERREQUEST"]._serialized_start = 24
    _globals["_ORDERREQUEST"]._serialized_end = 76
    _globals["_ORDERREPLY"]._serialized_start = 78
    _globals["_ORDERREPLY"]._serialized_end = 124
    _globals["_ORDERSERVICE"]._serialized_start = 126
    _globals["_ORDERSERVICE"]._serialized_end = 199
# @@protoc_insertion_point(module_scope)
