[project]
name = "modulo-cli-automatizacion"
version = "0.1.0"
description = ""
authors = [
    {name = "Erick Sebastian Meneses Navarro",email = "erick.meneses@axity.com"}
]
requires-python = ">=3.12"
dependencies = [
    "typer (>=0.27.2,<0.28.0)",
    "httpx (>=0.28.1,<0.29.0)",
    "pydantic-settings (>=2.15.0,<3.0.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[project.scripts]
gestor-ordenes = "modulo_cli_automatizacion.cli:app"
